# Processing - Climate Indices
- 해양 지역의 기상학적 변수를 기반으로 계산되는 전지구 단위 기후 인덱스
- 따라서 시계열 자료 형태임.
## Variables
- NINO 3.4 : 태평양 특정 해역(5N-5S, 170W-120W)의 SST Anomaly
- IOD (Indian Ocean Dipole) : West Pole SST Anomaly (50E-70E, 10S-10N) 에서 East Pole SST Anomaly (90E-110E, 10S-0S) 를 뺀 값
- WVG (Western V Gradient) : 표준화된 WP SST Anomaly에서 표준화된 Nino 4 SST Anomaly를 뺀 값
  - Western Pacific (WP) : 130E-150E, 0-20N
  - Nino 4 (Central Pacific) : 160E-150W, 5S-5N
  - WVG는 '표준화(Z-score)'된 값의 차이를 사용함(Funk et al.)
  - WVG가 높음(+) -> 서태평양 온난, 중태평양 한랭(La Nina 경향) -> 동아프리카 가뭄 유발
- MEI (Multivariate ENSO Index) : 5가지 핵심 기상 변수(SST, SLP, U, V, OLR)를 복합적으로 결합하여 산출
  - Positive (+) : 값이 클수록 강력한 엘니뇨를 의미함. 전 지구적 기온 상승과 연관되며, IOD와 상호작용하여 동아프리카에 이상 기후를 유발함.
  - Negative (-) : 값이 작을수록 강력한 라니뇨를 의미함. 동아프리카 지역에 극심한 가뭄을 일으키는 주범으로 작용하는 경우가 많음.

In [1]:
import os
from google.colab import drive

drive.mount('/content/drive')

folder_path = '/content/drive/MyDrive/WFP Collab/subnational_price_prediction/data/climate_indices/raw'
file_nm1 = 'Climate_Indices_OISST_2007_2025.csv'
file_nm2 = 'MEI_v2_Indices_2007_2025.csv'

full_path1 = os.path.join(folder_path, file_nm1)
full_path2 = os.path.join(folder_path, file_nm2)

Mounted at /content/drive

In [12]:
from pathlib import Path

output_folder = Path('/content/drive/MyDrive/WFP Collab/subnational_price_prediction/data/climate_indices/processed')
output_folder.mkdir(parents=True, exist_ok=True)

output_path = output_folder / 'Climate_Indices_2007_2025.csv'
print(output_path.exists())

False

In [11]:
import pandas as pd

In [3]:
df_oisst = pd.read_csv(full_path1)
df_oisst.head()

,system:index,IOD_DMI,IOD_East_Anom,IOD_West_Anom,NINO34_Anom,Nino4_Z_Score,WP_Z_Score,Western_V_Gradient,date,month,system:time_start,.geo
0,0,0.238247,0.241656,0.479903,0.764076,0.750351,0.213274,-0.537076,2007-01-01,1,1167609600000,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,1,-0.278013,0.681069,0.403056,0.085724,0.584695,0.085728,-0.498967,2007-02-01,2,1170288000000,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,2,0.225589,-0.037487,0.188102,-0.088586,0.522214,-0.581260,-1.103474,2007-03-01,3,1172707200000,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,3,0.205854,-0.014185,0.191669,-0.112287,0.221742,0.008981,-0.212761,2007-04-01,4,1175385600000,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,4,0.335512,-0.021653,0.313858,-0.444339,-0.254615,-0.251120,0.003495,2007-05-01,5,1177977600000,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [4]:
df_oisst['year'] = df_oisst['date'].str[:4].astype(int)
df_oisst_f = df_oisst[['year', 'month', 'NINO34_Anom', 'IOD_DMI', 'Western_V_Gradient']]
df_oisst_f.head()

   year  month  NINO34_Anom   IOD_DMI  Western_V_Gradient
0  2007      1     0.764076  0.238247           -0.537076
1  2007      2     0.085724 -0.278013           -0.498967
2  2007      3    -0.088586  0.225589           -1.103474
3  2007      4    -0.112287  0.205854           -0.212761
4  2007      5    -0.444339  0.335512            0.003495

In [8]:
pd.DataFrame(df_oisst_f.value_counts('year')).T

year,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
count,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12

In [9]:
pd.DataFrame(df_oisst_f.value_counts('month')).T

month  1   2   3   4   5   6   7   8   9   10  11  12
count  19  19  19  19  19  19  19  19  19  19  19  19

In [14]:
df_mei = pd.read_csv(full_path2)
df_mei.head()

         date  Year  Month  MEI_v2
0  2007-01-01  2007      1    0.64
1  2007-02-01  2007      2    0.40
2  2007-03-01  2007      3   -0.19
3  2007-04-01  2007      4   -0.32
4  2007-05-01  2007      5   -0.41

In [15]:
pd.DataFrame(df_mei.value_counts('Year')).T

Year,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
count,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12

In [16]:
pd.DataFrame(df_mei.value_counts('Month')).T

Month  1   2   3   4   5   6   7   8   9   10  11  12
count  19  19  19  19  19  19  19  19  19  19  19  19

In [19]:
df_merged = pd.merge(df_oisst_f, df_mei, left_on=['year', 'month'], right_on=['Year', 'Month'], how='left').drop(columns=['date', 'Year', 'Month'])
df_merged.head()

   year  month  NINO34_Anom   IOD_DMI  Western_V_Gradient  MEI_v2
0  2007      1     0.764076  0.238247           -0.537076    0.64
1  2007      2     0.085724 -0.278013           -0.498967    0.40
2  2007      3    -0.088586  0.225589           -1.103474   -0.19
3  2007      4    -0.112287  0.205854           -0.212761   -0.32
4  2007      5    -0.444339  0.335512            0.003495   -0.41

In [20]:
pd.DataFrame(df_merged.value_counts('year')).T

year,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
count,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12

In [21]:
pd.DataFrame(df_merged.value_counts('month')).T

month  1   2   3   4   5   6   7   8   9   10  11  12
count  19  19  19  19  19  19  19  19  19  19  19  19

In [22]:
print(len(df_oisst_f))
print(len(df_mei))
print(len(df_merged))

228
228
228

In [23]:
df_merged.to_csv(output_path, index=False)